---

libvirt:
  images: /var/lib/libvirt/images
  uri: qemu:///system

image:
  # See https://yum.oracle.com/oracle-linux-templates.html
  url: https://yum.oracle.com/templates/OracleLinux/OL9/u2/x86_64/OL9U2_x86_64-kvm-b197.qcow
  path: "{{ (libvirt.images, 'OL9U2_x86_64-kvm-b197.qcow') | path_join }}"
  checksum: sha256:840345cb866837ac7cc7c347cd9a8196c3a17e9c054c613eda8c2a912434c956

vm:
  name: "{{ vm_name }}"
  vcpus: 1
  cpu: host
  memory: 1024
  disk: "{{ (libvirt.images, vm_name + '.qcow') | path_join }}"
  iso: "{{ (libvirt.images, vm_name + '.iso') | path_join }}"
  network: default
  type: kvm
  os: ol9

  packages:
    - NetworkManager-wifi
    - bash-completion
    - bind-utils
    - dnsmasq
    - firefox
    - gdm
    - gnome-shell-extension-top-icons
    - gnome-shell-extension-window-list
    - gnome-terminal
    - gnome-tweaks
    - kernel
    - oracle-backgrounds
    - pciutils
    - xdg-utils
    - xmlstarlet
#    - /mnt/data/GlobalProtect_UI_focal_rpm-6.2.0.rpm

  systemd:
    system:
      enable:
        - dnsmasq
      mask:
        - colord
        - geoclue
        - power-profiles-daemon
        - rsyslog
        - switcheroo-control
        - upower
    user:
      mask:
        - at-spi-dbus-bus
        - colord-session
        - "dbus-:1.2-org.gnome.Shell.CalendarServer@"
        - "dbus-:1.2-org.gnome.Shell.Notifications@"
        - evolution-addressbook-factory
        - evolution-calendar-factory
        - evolution-source-registry
        - evolution-user-prompter
        - org.gnome.SettingsDaemon.A11ySettings
        - org.gnome.SettingsDaemon.Color
        - org.gnome.SettingsDaemon.Datetime
        - org.gnome.SettingsDaemon.Housekeeping
        - org.gnome.SettingsDaemon.Keyboard
        - org.gnome.SettingsDaemon.MediaKeys
        - org.gnome.SettingsDaemon.Power
        - org.gnome.SettingsDaemon.PrintNotifications
        - org.gnome.SettingsDaemon.Rfkill
        - org.gnome.SettingsDaemon.ScreensaverProxy
        - org.gnome.SettingsDaemon.Sharing
        - org.gnome.SettingsDaemon.Smartcard
        - org.gnome.SettingsDaemon.Sound
        - org.gnome.SettingsDaemon.Subscription
        - org.gnome.SettingsDaemon.UsbProtection
        - org.gnome.SettingsDaemon.Wacom
        - org.gnome.SettingsDaemon.XSettings
        - pipewire
        - pipewire.socket
        - pipewire-pulse
        - pipewire-pulse.socket
        - wireplumber
        - xdg-desktop-portal
        - xdg-document-portal
        - xdg-permission-store

  user:
    name: "{{ ansible_user_id }}"
    gecos: "{{ ansible_user_gecos }}"
    groups:
      - adm
      - systemd-journal
      - wheel
    home: "{{ ('/home', ansible_user_id) | path_join }}"
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_key: "{{ lookup('file', ansible_user_dir + '/.ssh/id_rsa.pub') }}"

host:
  # for slot in $(lspci | awk '/Ethernet|Network/ {print $1}'); do lspci -s "$slot" -Dknn; done
  device:
    id: "8086:2723"
    pci_id: "0000:03:00.0"
    domain: "0x0000"
    bus: "0x03"
    slot: "0x00"
    function: "0x0"

    # dmesg | grep 0000:03:00.0
    # find /usr/lib/firmware -name '*cc-a0-72.ucode*'
    # rpm -qf /usr/lib/firmware/iwlwifi-cc-a0-72.ucode.xz
    driver: iwlwifi
    firmware: iwlax2xx-firmware

    # lsmod | grep iwlwifi
    modules:
      - iwlmvm
      - iwlwifi

    vfio_modules:
      - vfio_iommu_type1
      - vfio_pci
      - vfio_pci_core
      - vfio
      - vfio_virqfd

  dns:
    search:
      - example.com
